# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created: Mon Jul 25 17:33:55 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(492, 447)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/charset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelArchivo = QtGui.QLabel(self.centralwidget)
        self.labelArchivo.setGeometry(QtCore.QRect(10, 170, 61, 20))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.labelArchivo.setFont(font)
        self.labelArchivo.setObjectName("labelArchivo")
        self.toolButtonBuscarArchivo = QtGui.QToolButton(self.centralwidget)
        self.toolButtonBuscarArchivo.setGeometry(QtCore.QRect(400, 190, 81, 24))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonBuscarArchivo.setIcon(icon1)
        self.toolButtonBuscarArchivo.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButtonBuscarArchivo.setObjectName("toolButtonBuscarArchivo")
        self.pushButtonSalir = QtGui.QPushButton(self.centralwidget)
        self.pushButtonSalir.setGeometry(QtCore.QRect(400, 410, 81, 24))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/application_exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonSalir.setIcon(icon2)
        self.pushButtonSalir.setObjectName("pushButtonSalir")
        self.toolButtonCargar = QtGui.QToolButton(self.centralwidget)
        self.toolButtonCargar.setEnabled(False)
        self.toolButtonCargar.setGeometry(QtCore.QRect(10, 230, 81, 24))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/exec.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonCargar.setIcon(icon3)
        self.toolButtonCargar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButtonCargar.setObjectName("toolButtonCargar")
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setEnabled(False)
        self.frame.setGeometry(QtCore.QRect(10, 270, 165, 50))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.graphicsViewCaptcha = QtGui.QGraphicsView(self.frame)
        self.graphicsViewCaptcha.setGeometry(QtCore.QRect(0, 0, 165, 50))
        self.graphicsViewCaptcha.setObjectName("graphicsViewCaptcha")
        self.toolButtonDescifrar = QtGui.QToolButton(self.centralwidget)
        self.toolButtonDescifrar.setEnabled(False)
        self.toolButtonDescifrar.setGeometry(QtCore.QRect(10, 330, 91, 24))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/games_solve.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonDescifrar.setIcon(icon4)
        self.toolButtonDescifrar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButtonDescifrar.setObjectName("toolButtonDescifrar")
        self.toolButtonBuscarCarpeta = QtGui.QToolButton(self.centralwidget)
        self.toolButtonBuscarCarpeta.setGeometry(QtCore.QRect(400, 30, 81, 24))
        self.toolButtonBuscarCarpeta.setIcon(icon1)
        self.toolButtonBuscarCarpeta.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButtonBuscarCarpeta.setObjectName("toolButtonBuscarCarpeta")
        self.lineEditCarpeta = QtGui.QLineEdit(self.centralwidget)
        self.lineEditCarpeta.setEnabled(False)
        self.lineEditCarpeta.setGeometry(QtCore.QRect(10, 30, 381, 25))
        self.lineEditCarpeta.setText("")
        self.lineEditCarpeta.setObjectName("lineEditCarpeta")
        self.labelCarpeta = QtGui.QLabel(self.centralwidget)
        self.labelCarpeta.setGeometry(QtCore.QRect(10, 10, 171, 20))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.labelCarpeta.setFont(font)
        self.labelCarpeta.setObjectName("labelCarpeta")
        self.toolButtonEntrenar = QtGui.QToolButton(self.centralwidget)
        self.toolButtonEntrenar.setEnabled(False)
        self.toolButtonEntrenar.setGeometry(QtCore.QRect(10, 60, 91, 24))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/alarmclock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonEntrenar.setIcon(icon5)
        self.toolButtonEntrenar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButtonEntrenar.setObjectName("toolButtonEntrenar")
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(False)
        self.progressBar.setGeometry(QtCore.QRect(10, 130, 118, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.lineEditArchivo = QtGui.QLineEdit(self.centralwidget)
        self.lineEditArchivo.setEnabled(False)
        self.lineEditArchivo.setGeometry(QtCore.QRect(10, 190, 381, 25))
        self.lineEditArchivo.setText("")
        self.lineEditArchivo.setObjectName("lineEditArchivo")
        self.labelProgress = QtGui.QLabel(self.centralwidget)
        self.labelProgress.setEnabled(False)
        self.labelProgress.setGeometry(QtCore.QRect(10, 110, 171, 16))
        self.labelProgress.setText("")
        self.labelProgress.setObjectName("labelProgress")
        self.toolButtonModificar = QtGui.QToolButton(self.centralwidget)
        self.toolButtonModificar.setEnabled(False)
        self.toolButtonModificar.setGeometry(QtCore.QRect(200, 370, 95, 25))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonModificar.setIcon(icon6)
        self.toolButtonModificar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButtonModificar.setObjectName("toolButtonModificar")
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setGeometry(QtCore.QRect(12, 372, 31, 31))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_4 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_4.setEnabled(False)
        self.lineEdit_4.setGeometry(QtCore.QRect(116, 372, 31, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_5.setEnabled(False)
        self.lineEdit_5.setGeometry(QtCore.QRect(151, 372, 31, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_2 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setGeometry(QtCore.QRect(47, 372, 31, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_3.setEnabled(False)
        self.lineEdit_3.setGeometry(QtCore.QRect(82, 372, 31, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.labelArchivo.setBuddy(self.lineEditArchivo)
        self.labelCarpeta.setBuddy(self.lineEditCarpeta)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.toolButtonBuscarArchivo, QtCore.SIGNAL("clicked(bool)"), self.lineEditArchivo.setDisabled)
        QtCore.QObject.connect(self.toolButtonBuscarArchivo, QtCore.SIGNAL("clicked(bool)"), self.toolButtonCargar.setDisabled)
        QtCore.QObject.connect(self.toolButtonCargar, QtCore.SIGNAL("clicked(bool)"), self.toolButtonDescifrar.setDisabled)
        QtCore.QObject.connect(self.toolButtonDescifrar, QtCore.SIGNAL("clicked(bool)"), self.lineEdit.setDisabled)
        QtCore.QObject.connect(self.toolButtonDescifrar, QtCore.SIGNAL("clicked(bool)"), self.lineEdit_5.setDisabled)
        QtCore.QObject.connect(self.toolButtonDescifrar, QtCore.SIGNAL("clicked(bool)"), self.lineEdit_4.setDisabled)
        QtCore.QObject.connect(self.toolButtonDescifrar, QtCore.SIGNAL("clicked(bool)"), self.lineEdit_3.setDisabled)
        QtCore.QObject.connect(self.toolButtonDescifrar, QtCore.SIGNAL("clicked(bool)"), self.lineEdit_2.setDisabled)
        QtCore.QObject.connect(self.toolButtonDescifrar, QtCore.SIGNAL("clicked(bool)"), self.toolButtonModificar.setDisabled)
        QtCore.QObject.connect(self.toolButtonBuscarCarpeta, QtCore.SIGNAL("clicked(bool)"), self.lineEditCarpeta.setDisabled)
        QtCore.QObject.connect(self.toolButtonBuscarCarpeta, QtCore.SIGNAL("clicked(bool)"), self.toolButtonEntrenar.setDisabled)
        QtCore.QObject.connect(self.toolButtonEntrenar, QtCore.SIGNAL("clicked(bool)"), self.labelProgress.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.toolButtonBuscarCarpeta, self.lineEditCarpeta)
        MainWindow.setTabOrder(self.lineEditCarpeta, self.toolButtonEntrenar)
        MainWindow.setTabOrder(self.toolButtonEntrenar, self.toolButtonBuscarArchivo)
        MainWindow.setTabOrder(self.toolButtonBuscarArchivo, self.lineEditArchivo)
        MainWindow.setTabOrder(self.lineEditArchivo, self.toolButtonCargar)
        MainWindow.setTabOrder(self.toolButtonCargar, self.graphicsViewCaptcha)
        MainWindow.setTabOrder(self.graphicsViewCaptcha, self.toolButtonDescifrar)
        MainWindow.setTabOrder(self.toolButtonDescifrar, self.lineEdit)
        MainWindow.setTabOrder(self.lineEdit, self.lineEdit_2)
        MainWindow.setTabOrder(self.lineEdit_2, self.lineEdit_3)
        MainWindow.setTabOrder(self.lineEdit_3, self.lineEdit_4)
        MainWindow.setTabOrder(self.lineEdit_4, self.lineEdit_5)
        MainWindow.setTabOrder(self.lineEdit_5, self.toolButtonModificar)
        MainWindow.setTabOrder(self.toolButtonModificar, self.pushButtonSalir)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Captcha", None, QtGui.QApplication.UnicodeUTF8))
        self.labelArchivo.setText(QtGui.QApplication.translate("MainWindow", "Archivo:", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonBuscarArchivo.setText(QtGui.QApplication.translate("MainWindow", "Buscar", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSalir.setText(QtGui.QApplication.translate("MainWindow", "Salir", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonCargar.setText(QtGui.QApplication.translate("MainWindow", "Cargar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonDescifrar.setText(QtGui.QApplication.translate("MainWindow", "Descifrar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonBuscarCarpeta.setText(QtGui.QApplication.translate("MainWindow", "Buscar", None, QtGui.QApplication.UnicodeUTF8))
        self.labelCarpeta.setText(QtGui.QApplication.translate("MainWindow", "Entrenar red con carpeta:", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonEntrenar.setText(QtGui.QApplication.translate("MainWindow", "Entrenar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonModificar.setText(QtGui.QApplication.translate("MainWindow", "Modificar", None, QtGui.QApplication.UnicodeUTF8))

